"""Data manipulation and example training utilities."""

from FeDa4Fair.utils.constants import (
    ACS_EMPLOYMENT,
    ACS_INCOME,
    ACS_RACE,
    CROSS_DEVICE,
    CROSS_SILO,
    DEFAULT_SEED,
    DEFAULT_SENSITIVE_ATTRIBUTES,
    DEFAULT_TEST_SIZE,
    DEFAULT_TRAIN_VAL_TEST_SPLIT,
    DEMOGRAPHIC_PARITY,
    EMPLOYMENT_LABEL,
    EQUALIZED_ODDS,
    INCOME_LABEL,
    LEVEL_ATTRIBUTE,
    LEVEL_ATTRIBUTE_VALUE,
    LEVEL_VALUE,
    MARITAL_STATUS,
    MIN_BIAS_THRESHOLD,
    RACE,
    RACE_BIAS_LOWER_BOUND,
    RACE_BIAS_UPPER_BOUND,
    SEX,
)
from FeDa4Fair.utils.data_types import ProcessedSiloData
from FeDa4Fair.utils.data_utils import (
    balance_data,
    cap_samples,
    drop_data,
    flip_data,
    generate_bias_by_groups,
    generate_modification_dict,
    generate_multiobjective_bias,
)

__all__ = [
    "ACS_EMPLOYMENT",
    "ACS_INCOME",
    "ACS_RACE",
    "CROSS_DEVICE",
    "CROSS_SILO",
    "DEFAULT_SEED",
    "DEFAULT_SENSITIVE_ATTRIBUTES",
    "DEFAULT_TEST_SIZE",
    "DEFAULT_TRAIN_VAL_TEST_SPLIT",
    "DEMOGRAPHIC_PARITY",
    "EMPLOYMENT_LABEL",
    "EQUALIZED_ODDS",
    "INCOME_LABEL",
    "LEVEL_ATTRIBUTE",
    "LEVEL_ATTRIBUTE_VALUE",
    "LEVEL_VALUE",
    "MARITAL_STATUS",
    "MIN_BIAS_THRESHOLD",
    "RACE",
    "RACE_BIAS_LOWER_BOUND",
    "RACE_BIAS_UPPER_BOUND",
    "SEX",
    "ProcessedSiloData",
    "balance_data",
    "cap_samples",
    "drop_data",
    "flip_data",
    "generate_bias_by_groups",
    "generate_modification_dict",
    "generate_multiobjective_bias",
]
